version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - automerge
  allow:
  - dependency-name: "@ecomplus/storefront-template"
  commit-message:
    prefix: fix
    include: scope
- package-ecosystem: npm
  directory: "/.netlify/functions/ssr"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - automerge
  allow:
  - dependency-name: "@ecomplus/storefront-renderer"
  commit-message:
    prefix: chore
    include: scope
